### ISSUE TITLE
Get available carriers

### ISSUE THREAD

**Issue by kytwb** [postmaster/postmaster-api#28]
Any endpoint for this?

**Comment by mrmarkfrench** [comment]
This would be a good addition for myself, as well.
Until an endpoint is available, is there a list published on a page somewhere that I could at least look at?

**Comment by mrmarkfrench** [comment]
It occurs to me that @kytwb and I might be asking different questions. I'm looking for a list of carriers supported for tracking external packages. An endpoint for supported carriers to send a package is likely also helpful.
