### ISSUE TITLE
Is UPS API Really Required?

### ISSUE THREAD

**Issue by maxapps** [postmaster/postmaster-api#39]
We have our client's UPS account number, username and password but they do not have a UPS API Key. Why is this required? I thought the whole point of using a service like this was to avoid having to deal with things like the incredibly poor UPS developer support site.

Please verify that this is a really a requirement because we're paying for the $30 API only access which quit working when we switched to the Postmaster production key (instead of using the test key).

**Comment by mentat** [comment]
Hi, yes, the UPS API key is required.  This is a carrier requirement.
