### ISSUE TITLE
Create Shipment Documentation: Incorrect "tracking" Response?

### ISSUE THREAD

**Issue by mattjanssen** [postmaster/postmaster-api#45]
The response example for **domestic** shipments has `"tracking": "1Z8V81310298744227"` but for **international** it's `"tracking": ["794808985444"]` within an array. But in our code, we're treating all shipment tracking responses as an array and it seems to be working.

Are we wrong, or are the docs wrong?

Also, how do we know which package got which tracking number? I assume the count of packages will always equal the count of tracking numbers. Are the arrays always in the same order then?

**Comment by mattjanssen** [comment]
https://www.postmaster.io/docs/api#create

**Comment by mentat** [comment]
This looks like a bug and will be fixed.
