### ISSUE TITLE
Temporary errors when trying to register shipments

### ISSUE THREAD

**Issue by hauru** [postmaster/postmaster-api#48]
For the last few days i've been getting the same error when calling `/v1/shipments` in the "sandbox" mode:

```
{"message": "Transient error, please try again later.", "code": 500, "details": {"body": {}, "code": 108}}
```
It worked earlier without any problems. Do you experience technical issues at the moment?

**Comment by dpmorel** [comment]
getting the same issue.  @hauru did you have any luck with this?

**Comment by hauru** [comment]
@dpmorel 

Nope. Tried to contact them directly via several e-mail accounts - no response. Looks like they've gone out of business. We've switched to a different API.

**Comment by ishaaqmuhammad** [comment]
Yes I got sometimes this temporary error and sometimes its working fine without any change.

Can one of you please guide me that can I integrate Postmaster api in Classic ASP????

Thank You
