### ISSUE TITLE
Get "Payment Required" error on POST /v1/validate on Testing Dashboard

### ISSUE THREAD

**Issue by ThoughtlessTHT** [postmaster/postmaster-api#57]
{"message": "APIError 402: Payment Required\n", "code": 400, "details": {"body": {"carrier_code": 402}, "code": 102}}

**Comment by ThoughtlessTHT** [comment]
And this error also occurs on production dashboard. CAn I get more informatio about it?

**Comment by ccasabona** [comment]
Same issue and same message.  Occurs in production and testing whether trying to process a shipment or validate an address.  Return message is:

{"message": "APIError 402: Payment Required\n", "code": 400, "details": {"body": {"carrier_code": 402}, "code": 102}}

Labels were processed in production last week with no trouble.

**Comment by ccasabona** [comment]
Re previous posts on 'Payment Required' error.  This appears to have been corrected as labels are processing correctly now

**Comment by ccasabona** [comment]
Problem is back today (9/29/15).  Error occurs when making a validation call using Postmaster::AddressValidation.validate().  Occurs on two sites with no changes being made on our end.  Label generation call is working.

**Comment by mentat** [comment]
Hi all, sorry about this.  The /validate issue has been resolved.

**Comment by ccasabona** [comment]
Jesse,

Thank you so much for resolving this!  

Charlie Casabona
